spring:
  application:
    name: Plot Manager
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: false

logging:
  level:
    fr.orionbs.plot_manager: debug
