spring:
  application:
    name: Plot Manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plot_manager_database
    username: root
    password: root-password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: false

logging:
  level:
    fr.orionbs.plot_manager: debug

  #persistence:
  # host: localhost
  #port: 3306
  #username: root
  #password: rootpassword
  #database: plot_manager_database



