spring:
  application:
    name: Plot Manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    open-in-view: false
    generate-ddl: false

logging:
  level:
    fr.orionbs.plot_manager: debug

persistence:
  host: localhost
  port: 3306
  username: root
  password: rootpassword
  database: plot_manager_database



