logging:
  level:
    fr.orionbs.plot_manager: debug

persistence:
  host: localhost
  port: 3306
  username: root
  password: rootpassword
  database: plot_updater_database

spring:
  application:
    name: PlotUpdaterProject
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: false

